### ISSUE TITLE
doesn't open window anymore

### ISSUE THREAD

**Issue by mzero** [my-flow/paypalimporter#16] opened 2021-05-12 18:08 UTC
In Moneydance 2021.1 (3067) the v7 of the importer doesn't do anything when you select **Download PayPal Transactions...**. No window appears, and there is nothing logged to the console.

**Comment by my-flow** [comment] 2021-06-14 04:14
Thanks! Duplicate of #15.

**Closed by my-flow** 2021-06-14 04:14 UTC
