### ISSUE TITLE
Paypalimporter does not load on Mac with MD2021.1(3069)

### ISSUE THREAD

**Issue by yogi1967** [my-flow/paypalimporter#17] opened 2021-06-12 09:37 UTC
The LaF changed after MD2021(2006) and the Mac now uses VAQua. I suspect this is causing the issue. But there is no error in console log. It's just silent and doesn't run on 2021.1 on Mac. It's fine on Linux and probably Windows too...

**Comment by my-flow** [comment] 2021-06-14 04:14
Thanks! Duplicate of #15.

**Closed by my-flow** 2021-06-14 04:14 UTC
Labels: duplicate

**Comment by yogi1967** [comment] 2021-06-14 04:42
Hi. Can you check your other extensions too. Others are failing also due to Vaqua. Thanks.
